[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
identity_program = "YOUR_SOLANA_PROGRAM_ID_HERE"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"