[toolchain]
anchor_version = "0.30.1"

[programs.localnet]
identity_program = "HU18d3qUrvLK52mQ2AoNKEnV6m1B6VreZ8M7eUE5GBew"

[provider]
cluster = "devnet"
wallet = "/home/copym/new-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
