[package]
name = "identity_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.0"
wormhole-anchor-sdk = "0.1.0"
anchor-spl = "0.30.0"

[profile.release]
overflow-checks = true
